#!/usr/bin/env node
// Build the SQLite database from the JSON data generated by the research workflow

const Database = require('better-sqlite3')
const fs = require('fs')
const path = require('path')

const DB_PATH = path.join(__dirname, '../data/capabilities.db')
const DATA_PATH = path.join(__dirname, '../data/capabilities.json')
const SCHEMA_PATH = path.join(__dirname, '../src/schema.sql')

if (!fs.existsSync(DATA_PATH)) {
  console.error('capabilities.json not found. Run the research workflow first.')
  process.exit(1)
}

const data = JSON.parse(fs.readFileSync(DATA_PATH, 'utf8'))
const schema = fs.readFileSync(SCHEMA_PATH, 'utf8')

// Remove existing DB
if (fs.existsSync(DB_PATH)) fs.unlinkSync(DB_PATH)

const db = new Database(DB_PATH)
db.exec(schema)

const DOMAIN_META = {
  custody: { name: 'Digital Asset Custody', color: '#f59e0b', icon: '🏦', sort: 1 },
  wallets: { name: 'Wallet Infrastructure', color: '#10b981', icon: '👛', sort: 2 },
  stablecoins: { name: 'Stablecoins', color: '#6366f1', icon: '💵', sort: 3 },
  cbdc: { name: 'CBDC & Digital Money', color: '#ec4899', icon: '🏛️', sort: 4 },
  settlement: { name: 'Settlement & Clearing', color: '#14b8a6', icon: '⚡', sort: 5 },
  tokenisation: { name: 'Tokenisation & RWA', color: '#f97316', icon: '🔖', sort: 6 },
  defi_protocols: { name: 'DeFi & Protocols', color: '#8b5cf6', icon: '🔗', sort: 7 },
  security: { name: 'Security & Risk', color: '#ef4444', icon: '🛡️', sort: 8 },
  ai_agentic: { name: 'AI & Agentic Systems', color: '#06b6d4', icon: '🤖', sort: 9 },
  compliance_regulation: { name: 'Compliance & Regulation', color: '#84cc16', icon: '📋', sort: 10 },
}

const insertDomain = db.prepare(`INSERT OR REPLACE INTO domains (id, name, description, color, icon, sort_order) VALUES (?,?,?,?,?,?)`)
const insertL0 = db.prepare(`INSERT OR REPLACE INTO capabilities_l0 (id, domain_id, name, description, sort_order) VALUES (?,?,?,?,?)`)
const insertL1 = db.prepare(`INSERT OR REPLACE INTO capabilities_l1 (id, l0_id, domain_id, name, description, sort_order) VALUES (?,?,?,?,?,?)`)
const insertL2 = db.prepare(`INSERT OR REPLACE INTO capabilities_l2 (id, l1_id, l0_id, domain_id, name, description, sort_order) VALUES (?,?,?,?,?,?,?)`)
const insertL3 = db.prepare(`INSERT OR REPLACE INTO capabilities_l3 (id, l2_id, l1_id, l0_id, domain_id, name, description, maturity, sort_order) VALUES (?,?,?,?,?,?,?,?,?)`)
const insertReg = db.prepare(`INSERT OR REPLACE INTO regulatory_frameworks (id, name, short_name, description, status, effective_date, regulator, jurisdiction, jurisdiction_id) VALUES (?,?,?,?,?,?,?,?,?)`)
const insertPos = db.prepare(`INSERT OR REPLACE INTO periodic_positions (capability_id, element_symbol, period, group_num, category) VALUES (?,?,?,?,?)`)

const insertAll = db.transaction((domains, regulatory) => {
  let l0Count = 0, l1Count = 0, l2Count = 0, l3Count = 0

  // Insert domains
  for (const [domainId, meta] of Object.entries(DOMAIN_META)) {
    insertDomain.run(domainId, meta.name, null, meta.color, meta.icon, meta.sort)
  }

  // Insert capabilities from research
  for (const domainResult of (domains || [])) {
    const domainId = domainResult.key
    const domainData = domainResult.data
    if (!domainData || !domainData.l0_competencies) continue

    let l0Idx = 0
    for (const l0 of domainData.l0_competencies) {
      const l0id = l0.id || `${domainId}-l0-${l0Idx}`
      insertL0.run(l0id, domainId, l0.name, l0.description || null, l0Idx)
      l0Count++

      let l1Idx = 0
      for (const l1 of (l0.l1_capabilities || [])) {
        const l1id = l1.id || `${l0id}-l1-${l1Idx}`
        insertL1.run(l1id, l0id, domainId, l1.name, l1.description || null, l1Idx)
        l1Count++

        let l2Idx = 0
        for (const l2 of (l1.l2_technical || [])) {
          const l2id = l2.id || `${l1id}-l2-${l2Idx}`
          insertL2.run(l2id, l1id, l0id, domainId, l2.name, l2.description || null, l2Idx)
          l2Count++

          let l3Idx = 0
          for (const l3 of (l2.l3_features || [])) {
            const l3id = l3.id || `${l2id}-l3-${l3Idx}`
            const maturity = ['emerging','developing','established','mature'].includes(l3.maturity) ? l3.maturity : 'developing'
            insertL3.run(l3id, l2id, l1id, l0id, domainId, l3.name, l3.description || null, maturity, l3Idx)
            l3Count++
            l3Idx++
          }
          l2Idx++
        }
        l1Idx++
      }
      l0Idx++
    }
  }

  // Insert regulatory frameworks
  for (const regResult of (regulatory || [])) {
    if (!regResult?.data?.frameworks) continue
    const jId = regResult.key
    const jName = regResult.data.jurisdiction

    for (const fw of regResult.data.frameworks) {
      const fwId = fw.id || `${jId}-${fw.shortName || fw.name}`.toLowerCase().replace(/[^a-z0-9-]/g, '-').slice(0, 60)
      insertReg.run(
        fwId,
        fw.name,
        fw.shortName || null,
        fw.description || null,
        fw.status || null,
        fw.effectiveDate || null,
        fw.regulator || null,
        jName,
        jId
      )
    }
  }

  // Assign periodic table positions to L1 capabilities
  // Group by domain and lay out in columns
  const DOMAIN_COLS = {
    custody:               [1,2],
    wallets:               [3,4],
    stablecoins:           [5,6],
    cbdc:                  [7,8],
    settlement:            [9,10],
    tokenisation:          [11,12],
    defi_protocols:        [13,14],
    security:              [15,16],
    ai_agentic:            [17],
    compliance_regulation: [18],
  }

  const colPeriod = {}
  const l1sAll = db.prepare(`SELECT id, name, domain_id FROM capabilities_l1 ORDER BY domain_id, sort_order`).all()

  const domainL1s = {}
  for (const l1 of l1sAll) {
    if (!domainL1s[l1.domain_id]) domainL1s[l1.domain_id] = []
    domainL1s[l1.domain_id].push(l1)
  }

  for (const [domainId, l1s] of Object.entries(domainL1s)) {
    const cols = DOMAIN_COLS[domainId] || [1]
    let colIdx = 0
    for (const l1 of l1s) {
      const col = cols[colIdx % cols.length]
      if (!colPeriod[col]) colPeriod[col] = 1
      const sym = l1.name.split(/\s+/).slice(0,2).map(w => w[0]).join('').toUpperCase().slice(0,2)
      insertPos.run(l1.id, sym, colPeriod[col], col, domainId)
      colPeriod[col]++
      colIdx++
    }
  }

  console.log(`✓ L0: ${l0Count}, L1: ${l1Count}, L2: ${l2Count}, L3: ${l3Count}`)
  return { l0Count, l1Count, l2Count, l3Count }
})

const result = insertAll(data.domains, data.regulatory)
db.close()

console.log(`Database built: ${DB_PATH}`)
console.log(`Total L3 features: ${result.l3Count}`)
